using Contoso.Parameters.Expressions;

namespace Contoso.Bsl.Flow
{
    public class DummyOperatorParameterConstructor
    {
        public DummyOperatorParameterConstructor
        (
            AddBinaryOperatorParameter addBinaryOperatorParameter,
            AllOperatorParameter allOperatorParameter,
            AndBinaryOperatorParameter andBinaryOperatorParameter,
            AnyOperatorParameter anyOperatorParameter,
            AsQueryableOperatorParameter asQueryableOperatorParameter,
            AverageOperatorParameter averageOperatorParameter,
            BinaryOperatorParameter binaryOperatorParameter,
            CastOperatorParameter castOperatorParameter,
            CeilingOperatorParameter ceilingOperatorParameter,
            CollectionCastOperatorParameter collectionCastOperatorParameter,
            CollectionConstantOperatorParameter collectionConstantOperatorParameter,
            ConcatOperatorParameter concatOperatorParameter,
            ConstantOperatorParameter constantOperatorParameter,
            ContainsOperatorParameter containsOperatorParameter,
            ConvertCharArrayToStringOperatorParameter convertCharArrayToStringOperatorParameter,
            ConvertOperatorParameter convertOperatorParameter,
            ConvertToEnumOperatorParameter convertToEnumOperatorParameter,
            ConvertToNullableUnderlyingValueOperatorParameter convertToNullableUnderlyingValueOperatorParameter,
            ConvertToNumericDateOperatorParameter convertToNumericDateOperatorParameter,
            ConvertToNumericTimeOperatorParameter convertToNumericTimeOperatorParameter,
            ConvertToStringOperatorParameter convertToStringOperatorParameter,
            CountOperatorParameter countOperatorParameter,
            CustomMethodOperatorParameter customMethodOperatorParameter,
            DateOperatorParameter dateOperatorParameter,
            DayOperatorParameter dayOperatorParameter,
            DistinctOperatorParameter distinctOperatorParameter,
            DivideBinaryOperatorParameter divideBinaryOperatorParameter,
            EndsWithOperatorParameter endsWithOperatorParameter,
            EqualsBinaryOperatorParameter equalsBinaryOperatorParameter,
            FilterLambdaOperatorParameter filterLambdaOperatorParameter,
            FirstOperatorParameter firstOperatorParameter,
            FirstOrDefaultOperatorParameter firstOrDefaultOperatorParameter,
            FloorOperatorParameter floorOperatorParameter,
            FractionalSecondsOperatorParameter fractionalSecondsOperatorParameter,
            GreaterThanBinaryOperatorParameter greaterThanBinaryOperatorParameter,
            GreaterThanOrEqualsBinaryOperatorParameter greaterThanOrEqualsBinaryOperatorParameter,
            GroupByOperatorParameter groupByOperatorParameter,
            HasOperatorParameter hasOperatorParameter,
            HourOperatorParameter hourOperatorParameter,
            IEnumerableSelectorLambdaOperatorParameter enumerableSelectorLambdaOperatorParameter,
            InOperatorParameter inOperatorParameter,
            IndexOfOperatorParameter indexOfOperatorParameter,
            IsOfOperatorParameter isOfOperatorParameter,
            LastOperatorParameter lastOperatorParameter,
            LastOrDefaultOperatorParameter lastOrDefaultOperatorParameter,
            LengthOperatorParameter lengthOperatorParameter,
            LessThanBinaryOperatorParameter lessThanBinaryOperatorParameter,
            LessThanOrEqualsBinaryOperatorParameter lessThanOrEqualsBinaryOperatorParameter,
            MaxDateTimeOperatorParameter maxDateTimeOperatorParameter,
            MaxOperatorParameter maxOperatorParameter,
            MemberInitOperatorParameter memberInitOperatorParameter,
            MemberSelectorOperatorParameter memberSelectorOperatorParameter,
            MinDateTimeOperatorParameter minDateTimeOperatorParameter,
            MinOperatorParameter minOperatorParameter,
            MinuteOperatorParameter minuteOperatorParameter,
            ModuloBinaryOperatorParameter moduloBinaryOperatorParameter,
            MonthOperatorParameter monthOperatorParameter,
            MultiplyBinaryOperatorParameter multiplyBinaryOperatorParameter,
            NegateOperatorParameter negateOperatorParameter,
            NotOperatorParameter notOperatorParameter,
            NotEqualsBinaryOperatorParameter notEqualsBinaryOperatorParameter,
            NowDateTimeOperatorParameter nowDateTimeOperatorParameter,
            OrBinaryOperatorParameter orBinaryOperatorParameter,
            OrderByOperatorParameter orderByOperatorParameter,
            ParameterOperatorParameter parameterOperatorParameter,
            RoundOperatorParameter roundOperatorParameter,
            SecondOperatorParameter secondOperatorParameter,
            SelectOperatorParameter selectOperatorParameter,
            SelectManyOperatorParameter selectManyOperatorParameter,
            SelectorLambdaOperatorParameter selectorLambdaOperatorParameter,
            SingleOperatorParameter singleOperatorParameter,
            SingleOrDefaultOperatorParameter singleOrDefaultOperatorParameter,
            SkipOperatorParameter skipOperatorParameter,
            StartsWithOperatorParameter startsWithOperatorParameter,
            SubstringOperatorParameter substringOperatorParameter,
            SubtractBinaryOperatorParameter subtractBinaryOperatorParameter,
            SumOperatorParameter sumOperatorParameter,
            TakeOperatorParameter takeOperatorParameter,
            ThenByOperatorParameter thenByOperatorParameter,
            TimeOperatorParameter timeOperatorParameter,
            ToListOperatorParameter toListOperatorParameter,
            ToLowerOperatorParameter toLowerOperatorParameter,
            TotalOffsetMinutesOperatorParameter totalOffsetMinutesOperatorParameter,
            TotalSecondsOperatorParameter totalSecondsOperatorParameter,
            ToUpperOperatorParameter toUpperOperatorParameter,
            TrimOperatorParameter trimOperatorParameter,
            WhereOperatorParameter whereOperatorParameter,
            YearOperatorParameter yearOperatorParameter
        )
        {

        }
    }
}
