using LogicBuilder.Expressions.Utils.ExpressionDescriptors;
using System;
using System.Collections.Generic;
using System.Text;

namespace Contoso.Bsl.Flow
{
    public class DummyDescriptorConstructor
    {
        public DummyDescriptorConstructor
        (
            AddBinaryDescriptor addBinaryDescriptor,
            AllDescriptor allDescriptor,
            AndBinaryDescriptor andBinaryDescriptor,
            AnyDescriptor anyDescriptor,
            AsQueryableDescriptor asQueryableDescriptor,
            AverageDescriptor averageDescriptor,
            BinaryDescriptor binaryDescriptor,
            CastDescriptor castDescriptor,
            CeilingDescriptor ceilingDescriptor,
            CollectionCastDescriptor collectionCastDescriptor,
            CollectionConstantDescriptor collectionConstantDescriptor,
            ConcatDescriptor concatDescriptor,
            ConstantDescriptor constantDescriptor,
            ContainsDescriptor containsDescriptor,
            ConvertCharArrayToStringDescriptor convertCharArrayToStringDescriptor,
            ConvertDescriptor convertDescriptor,
            ConvertToEnumDescriptor convertToEnumDescriptor,
            ConvertToNullableUnderlyingValueDescriptor convertToNullableUnderlyingValueDescriptor,
            ConvertToNumericDateDescriptor convertToNumericDateDescriptor,
            ConvertToNumericTimeDescriptor convertToNumericTimeDescriptor,
            ConvertToStringDescriptor convertToStringDescriptor,
            CountDescriptor countDescriptor,
            CustomMethodDescriptor customMethodDescriptor,
            DateDescriptor dateDescriptor,
            DayDescriptor dayDescriptor,
            DistinctDescriptor distinctDescriptor,
            DivideBinaryDescriptor divideBinaryDescriptor,
            EndsWithDescriptor endsWithDescriptor,
            EqualsBinaryDescriptor equalsBinaryDescriptor,
            FilterLambdaDescriptor filterLambdaDescriptor,
            FirstDescriptor firstDescriptor,
            FirstOrDefaultDescriptor firstOrDefaultDescriptor,
            FloorDescriptor floorDescriptor,
            FractionalSecondsDescriptor fractionalSecondsDescriptor,
            GreaterThanBinaryDescriptor greaterThanBinaryDescriptor,
            GreaterThanOrEqualsBinaryDescriptor greaterThanOrEqualsBinaryDescriptor,
            GroupByDescriptor groupByDescriptor,
            HasDescriptor hasDescriptor,
            HourDescriptor hourDescriptor,
            IEnumerableSelectorLambdaDescriptor enumerableSelectorLambdaDescriptor,
            InDescriptor inDescriptor,
            IndexOfDescriptor indexOfDescriptor,
            IsOfDescriptor isOfDescriptor,
            LastDescriptor lastDescriptor,
            LastOrDefaultDescriptor lastOrDefaultDescriptor,
            LengthDescriptor lengthDescriptor,
            LessThanBinaryDescriptor lessThanBinaryDescriptor,
            LessThanOrEqualsBinaryDescriptor lessThanOrEqualsBinaryDescriptor,
            MaxDateTimeDescriptor maxDateTimeDescriptor,
            MaxDescriptor maxDescriptor,
            MemberInitDescriptor memberInitDescriptor,
            MemberSelectorDescriptor memberSelectorDescriptor,
            MinDateTimeDescriptor minDateTimeDescriptor,
            MinDescriptor minDescriptor,
            MinuteDescriptor minuteDescriptor,
            ModuloBinaryDescriptor moduloBinaryDescriptor,
            MonthDescriptor monthDescriptor,
            MultiplyBinaryDescriptor multiplyBinaryDescriptor,
            NegateDescriptor negateDescriptor,
            NotDescriptor notDescriptor,
            NotEqualsBinaryDescriptor notEqualsBinaryDescriptor,
            NowDateTimeDescriptor nowDateTimeDescriptor,
            OrBinaryDescriptor orBinaryDescriptor,
            OrderByDescriptor orderByDescriptor,
            ParameterDescriptor parameterDescriptor,
            RoundDescriptor roundDescriptor,
            SecondDescriptor secondDescriptor,
            SelectDescriptor selectDescriptor,
            SelectManyDescriptor selectManyDescriptor,
            SelectorLambdaDescriptor selectorLambdaDescriptor,
            SingleDescriptor singleDescriptor,
            SingleOrDefaultDescriptor singleOrDefaultDescriptor,
            SkipDescriptor skipDescriptor,
            StartsWithDescriptor startsWithDescriptor,
            SubstringDescriptor substringDescriptor,
            SubtractBinaryDescriptor subtractBinaryDescriptor,
            SumDescriptor sumDescriptor,
            TakeDescriptor takeDescriptor,
            ThenByDescriptor thenByDescriptor,
            TimeDescriptor timeDescriptor,
            ToListDescriptor toListDescriptor,
            ToLowerDescriptor toLowerDescriptor,
            TotalOffsetMinutesDescriptor totalOffsetMinutesDescriptor,
            TotalSecondsDescriptor totalSecondsDescriptor,
            ToUpperDescriptor toUpperDescriptor,
            TrimDescriptor trimDescriptor,
            WhereDescriptor whereDescriptor,
            YearDescriptor yearDescriptor
        )
        {

        }
    }
}
